"""empty message

Revision ID: 58baffaa77cf
Revises: f90d4cbb8a1f
Create Date: 2021-09-06 12:16:17.937284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58baffaa77cf'
down_revision = 'f90d4cbb8a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
